# -*- coding: utf-8 -*-
# Part of Softhealer Technologies.
{
    'name': 'Theme Softhealer Website',
    'author': 'Softhealer Technologies',
    'website': 'https://www.softhealer.com',
    'support': 'support@softhealer.com',
    'category': 'Theme/Website',
    'summary': 'Theme Softhealer Website',
    'description': '''Theme Softhealer Website''',
    'version': '16.0.4',
    'depends': ['website', 'website_crm', 'website_blog', 'website_mass_mailing','sh_helpdesk', 'softhealer_website_base','auth_totp'],
    'application': True,
    'data': [
        # Readymade Pages
        "security/ir.model.access.csv",
        'data/website_data.xml',
        'data/ir_model_data.xml',
        'views/website_blog_templates.xml',
        # 'views/pages/about_us_page.xml',
        'views/pages/about_us_page_new.xml',
        'views/pages/appointment_mngmt_page.xml',
        'views/pages/access_mngmt_page.xml',
        'views/pages/genie_360_page.xml',
        'views/pages/bus_booking_mngmt_page.xml',
        # 'views/sh_helpdesk.xml',
        #'views/pages/contact_us_page.xml',
        'views/pages/contact_us_page_new.xml',
        'views/pages/crm_solution_page.xml',
        'views/pages/custom_software_page.xml',
        'views/pages/erp_solution_page.xml',
        'views/pages/event_seat_booking_mngmt_page.xml',
        'views/pages/helpdesk_mngmt_system_page.xml',
        'views/pages/hotel_mngmt_system_page.xml',
        'views/pages/home_page.xml',
        'views/pages/hrms_page.xml',
        'views/pages/law_mngmt_system_page.xml',
        'views/pages/laundry_mngmt_system_page.xml',
        'views/pages/mission_vision_value_page.xml',
        'views/pages/mobile_app_development_page.xml',
        'views/pages/odoo_customization_page.xml',
        'views/pages/odoo_implementation_page.xml',
        'views/pages/odoo_migration_page.xml',
        'views/pages/odoo_services_page.xml',
        'views/pages/odoo_support_page.xml',
        'views/pages/odoo_training_page.xml',
        'views/pages/parking_mngmt_system_page.xml',
        'views/pages/pathology_lab_mngmt_system_page.xml',
        'views/pages/pos_retail_shop_page.xml',
        'views/pages/pos_retail_shop_with_ksa_page.xml',
        'views/pages/pos_solution_page.xml',
        'views/pages/project_mngmt_system_page.xml',
        'views/pages/optical_mngmt_system_page.xml',
        'views/pages/readymade_solution_page.xml',
        'views/pages/survey_mngmt_system_page.xml',
        'views/pages/third_party_app_page.xml',
        'views/pages/third_party_app_taxjar_connector_page.xml',
        'views/pages/third_party_app_trello_odoo_connector_app_page.xml',
        'views/pages/visitor_mngmt_system_page.xml',
        'views/pages/web_development_page.xml',
        'views/pages/why_softhealer_services_page.xml',
        'views/pages/odoo_sass_migration_page.xml',
        #'views/pages/privacy_policy.xml',
        'views/pages/privacy_policy_page_new.xml',
        'views/pages/meet_us.xml',
        'views/pages/crm_advance.xml',
        'views/pages/zoho_sales_crm_page.xml',
        'views/pages/zoho_project_page.xml',
        'views/pages/zoho_book_accounting_page.xml',
        'views/pages/zoho_creator_page.xml',
        'views/pages/zoho_payroll_page.xml',
        'views/pages/zoho_service_page.xml',
        'views/pages/sap_service_page.xml',
        'views/pages/sap_hana_page.xml',
        'views/pages/insurance_mngmt_system_page.xml',
        'views/pages/subscription_management_page.xml',
        'views/pages/petrol_mngmt_system_page.xml',
        'views/pages/auto_parts_mngmt_system_page.xml',
        'views/pages/tender_management_page.xml',
        'views/pages/royal_paint_page.xml',
        'views/pages/musical_institute_mngmt_system_page.xml',
        'views/pages/property_mngmt_system_page.xml',
        'views/pages/client_visit_2024_page.xml',
        'views/pages/fun_activity_2024_page.xml',
        'views/pages/hardware_store.xml',
        'views/pages/life_At_softhealer.xml',
        'views/pages/solar_management.xml',
        'views/pages/abc.xml',
        'views/pages/test_artical_blog.xml',
        'views/pages/pushpa_2.xml',
        'views/pages/heal_station.xml',
        'views/pages/cooking_compition_2025.xml',
        'views/pages/best_odoo_services_in_dubai.xml',
        'views/pages/cricket_Tournament_2025.xml',
        'views/pages/test_blog.xml',
        'views/sh_image_slider_snippet_views.xml',
        'views/sh_image_slider_template.xml',
        'views/snippets/sh_image_slider_snippet.xml',
        # "views/helpdesk_ticket.xml",
        'views/pages/uae_home_page.xml',
        'views/pages/hire_developer_page.xml',
        'views/pages/vehicle_rental_management_page.xml',
        'views/pages/tailoring_management_page.xml',
        'views/pages/germany_home_page.xml',
        'views/pages/vehicle_rental_management_page_2.xml',
        'views/pages/canada_home_page.xml',

        
        

        # common backend templates
        "views/snippets/snippets.xml",

        # Menu
        'data/menu.xml',
        'views/website_blog_post_templates.xml',

        "views/website_layout.xml",
        #auth_totp
        "views/auth_totp_templates.xml"
    ],
    'assets': {
        'web.assets_frontend': [

            'theme_softhealer_website/static/src/scss/custom_variables.scss',
            'theme_softhealer_website/static/src/scss/mixin.scss',
            'theme_softhealer_website/static/src/scss/about_us_page.scss',
            'theme_softhealer_website/static/src/scss/appointment_mngmt_page.scss',
            'theme_softhealer_website/static/src/scss/access_mngmt_page.scss',
            'theme_softhealer_website/static/src/scss/genie_360.scss',
            'theme_softhealer_website/static/src/scss/bus_booking_mngmt_page.scss',
            'theme_softhealer_website/static/src/scss/contact_us_page.scss',
            'theme_softhealer_website/static/src/scss/crm_solution_page.scss',
            'theme_softhealer_website/static/src/scss/custom_software_page.scss',
            'theme_softhealer_website/static/src/scss/erp_solution_page.scss',
            'theme_softhealer_website/static/src/scss/event_seat_booking_mngmt_page.scss',
            'theme_softhealer_website/static/src/scss/global_search.scss',
            'theme_softhealer_website/static/src/scss/helpdesk_mngmt_system_page.scss',
            'theme_softhealer_website/static/src/scss/hotel_mngmt_system_page.scss',
            'theme_softhealer_website/static/src/scss/home_page.scss',
            'theme_softhealer_website/static/src/scss/hrms_page.scss',
            'theme_softhealer_website/static/src/scss/law_mngmt_system_page.scss',
            'theme_softhealer_website/static/src/scss/laundry_mngmt_system_page.scss',
            'theme_softhealer_website/static/src/scss/mission_vision_value_page.scss',
            'theme_softhealer_website/static/src/scss/mobile_app_development_page.scss',
            'theme_softhealer_website/static/src/scss/odoo_customization_page.scss',
            'theme_softhealer_website/static/src/scss/odoo_implementation_page.scss',
            'theme_softhealer_website/static/src/scss/odoo_migration_page.scss',
            'theme_softhealer_website/static/src/scss/odoo_services_page.scss',
            'theme_softhealer_website/static/src/scss/odoo_support_page.scss',
            'theme_softhealer_website/static/src/scss/odoo_training_page.scss',
            'theme_softhealer_website/static/src/scss/odoo_services_page.scss',
            'theme_softhealer_website/static/src/scss/parking_mngmt_system_page.scss',
            'theme_softhealer_website/static/src/scss/pathology_lab_mngmt_system_page.scss',
            'theme_softhealer_website/static/src/scss/pos_retail_shop_page.scss',
            'theme_softhealer_website/static/src/scss/pos_retail_shop_with_ksa_page.scss',
            'theme_softhealer_website/static/src/scss/pos_solution_page.scss',
            'theme_softhealer_website/static/src/scss/project_mngmt_system_page.scss',
            'theme_softhealer_website/static/src/scss/optical_mngmt_system_page.scss',
            'theme_softhealer_website/static/src/scss/readymade_solution_page.scss',
            'theme_softhealer_website/static/src/scss/survey_mngmt_system_page.scss',
            'theme_softhealer_website/static/src/scss/third_party_app_page.scss',
            'theme_softhealer_website/static/src/scss/third_party_app_taxjar_connector_page.scss',
            'theme_softhealer_website/static/src/scss/third_party_app_trello_odoo_connector_app_page.scss',
            'theme_softhealer_website/static/src/scss/visitor_mngmt_system_page.scss',
            'theme_softhealer_website/static/src/scss/web_development_page.scss',
            'theme_softhealer_website/static/src/scss/why_softhealer_services_page.scss',
            'theme_softhealer_website/static/src/scss/login_page.scss',
            'theme_softhealer_website/static/src/scss/support.scss',
            'theme_softhealer_website/static/src/scss/privacy_policy.scss',
            'theme_softhealer_website/static/src/scss/meet_us.scss',
            'theme_softhealer_website/static/src/scss/crm_advance.scss',
            'theme_softhealer_website/static/src/scss/zoho_sales_page.scss',
            'theme_softhealer_website/static/src/scss/zoho_project_page.scss',
            'theme_softhealer_website/static/src/scss/zoho_book_accounting_page.scss',
            'theme_softhealer_website/static/src/scss/zoho_creator_page.scss',
            'theme_softhealer_website/static/src/scss/zoho_payroll_page.scss',
            'theme_softhealer_website/static/src/scss/zoho_service_page.scss',
            'theme_softhealer_website/static/src/scss/sap_service_page.scss',
            'theme_softhealer_website/static/src/scss/sap_hana_page.scss',
            'theme_softhealer_website/static/src/scss/petrol_mngmt_system_page.scss',
            'theme_softhealer_website/static/src/scss/odoo_sass_migration.scss',
            'theme_softhealer_website/static/src/scss/insurance_mngmt_system_page.scss',
            'theme_softhealer_website/static/src/scss/subscription_management_page.scss',
            'theme_softhealer_website/static/src/scss/auto_parts_mngmt_page.scss',
            'theme_softhealer_website/static/src/scss/tender_management_page.scss',
            'theme_softhealer_website/static/src/scss/musical_mngmt_system_page.scss',
            'theme_softhealer_website/static/src/scss/royal_paint_page.scss',
            # 'theme_softhealer_website/static/src/scss/what_is_migration_blog_page.scss',
            # 'theme_softhealer_website/static/src/scss/odoo_implementation_blog_page.scss',
            # 'theme_softhealer_website/static/src/scss/importance_of_odoo_implementation_blog_page.scss',
            # 'theme_softhealer_website/static/src/scss/why_odoo_overview_of_key_module_blog_page.scss',
            # 'theme_softhealer_website/static/src/scss/integrate_ecommerce_with_odoo_erp_blog_page.scss',
            # 'theme_softhealer_website/static/src/scss/odoo_erp_for_business_blog_page.scss',
            # 'theme_softhealer_website/static/src/scss/odoo_crm_guide_blog_page.scss',
            # 'theme_softhealer_website/static/src/scss/pos_software_for_retail_business_blog_page.scss',
            # 'theme_softhealer_website/static/src/scss/odoo_erp_for_manufacturing_blog_page.scss',
            # 'theme_softhealer_website/static/src/scss/things_to_know_before_odoo_migration_blog_page.scss',
            # 'theme_softhealer_website/static/src/scss/things_to_know_before_odoo_implementation_blog_page.scss',
            # 'theme_softhealer_website/static/src/scss/why_odoo_better_other_erp_blog_page.scss',
            # 'theme_softhealer_website/static/src/scss/logistic_management_system_blog_page.scss',
            # 'theme_softhealer_website/static/src/scss/odoo_erp_for_diffrent_industry_blog_page.scss',
            # 'theme_softhealer_website/static/src/scss/right_odoo_implementation_industry_blog_page.scss',
            # 'theme_softhealer_website/static/src/scss/why_odoo_erp_choice_for__business_management_blog_page.scss',
            # 'theme_softhealer_website/static/src/scss/why_odoo_erp_best_for_retail_business_blog_page.scss',
            # 'theme_softhealer_website/static/src/scss/need_odoo_support_and_maintanance_blog_page.scss',
            'theme_softhealer_website/static/src/scss/odoo_erp_cost_effective_blog_page.scss',
            # 'theme_softhealer_website/static/src/scss/real_state_management_blog_page.scss',
            # 'theme_softhealer_website/static/src/scss/hotel_management_best_choice_blog_page.scss',
            # 'theme_softhealer_website/static/src/scss/erp_solution_for_petrol_pump_business_blog_page.scss',
            # 'theme_softhealer_website/static/src/scss/choosing_right_partner_for_migration_blog_page.scss',
            # 'theme_softhealer_website/static/src/scss/odoo_inventory_management_blog_page.scss',
            # 'theme_softhealer_website/static/src/scss/why_odoo_erp_system_for_hotel_management.scss',
            # 'theme_softhealer_website/static/src/scss/logistic_supply_chain_management_blog_page.scss',
            # 'theme_softhealer_website/static/src/scss/how_odoo_erp_for_footwear_management_system.scss',
            # 'theme_softhealer_website/static/src/scss/best_choice_for_no_1_softhealer_2025_blog_page.scss',
            # 'theme_softhealer_website/static/src/scss/subscription_management_increase_revenue_page.scss',
            'theme_softhealer_website/static/src/scss/complete_tender_management_system_blog_page.scss',
            'theme_softhealer_website/static/src/scss/property_mngmt_page.scss',
            'theme_softhealer_website/static/src/scss/hardware_store.scss',
            'theme_softhealer_website/static/src/scss/life_at_softhealer.scss',
            'theme_softhealer_website/static/src/scss/solar_management.scss',
            'theme_softhealer_website/static/src/scss/best_odoo_services_in_dubai.scss',
            'theme_softhealer_website/static/src/scss/blogs_bkp/jaisalmer_blog_page.scss',
            'theme_softhealer_website/static/src/scss/hire_developers_page.scss',
            'theme_softhealer_website/static/src/scss/uae_home_page.scss',
            'theme_softhealer_website/static/src/scss/vehicle_mngmt_system_page.scss',
            'theme_softhealer_website/static/src/scss/tailoring_management_page.scss',
            'theme_softhealer_website/static/src/scss/germany_home_page.scss',
            'theme_softhealer_website/static/src/scss/canada_home_page.scss',


            # Website Jobs
            'theme_softhealer_website/static/src/scss/website_hr_recruitment.scss',

            # Website Blog
            'theme_softhealer_website/static/src/scss/website_blog.scss',
        
            ## Main Blog pages
            'theme_softhealer_website/static/src/scss/blog_page.scss',

            ## Career Page
            'theme_softhealer_website/static/src/scss/career_page.scss',

            # Header and Megamenu
            "theme_softhealer_website/static/src/scss/header_megamenu.scss",

            # scrollbar
            "theme_softhealer_website/static/src/scss/scrollbar.scss",

            # Owl carousel
            "theme_softhealer_website/static/src/lib/owl_carousel/owl.css",
            "theme_softhealer_website/static/src/lib/owl_carousel/owl.js",
            "theme_softhealer_website/static/src/lib/owl_carousel/owl_init.js",


            # AOS init
            # 'theme_softhealer_website/static/src/lib/aos/aos_extra.css',
            # 'theme_softhealer_website/static/src/lib/aos/aos.css',
            # 'theme_softhealer_website/static/src/lib/aos/aos.js',
            # 'theme_softhealer_website/static/src/lib/aos/layout.css',
            # 'theme_softhealer_website/static/src/lib/aos/aos_init.js',

            "theme_softhealer_website/static/src/js/counter.js",

            # page scroll down and back to top
            "theme_softhealer_website/static/src/js/common.js",
            "theme_softhealer_website/static/src/scss/common.scss",

            # CRM solution tab
            "theme_softhealer_website/static/src/js/crm_solution_tab.js",

            # call to action scroll js
            "theme_softhealer_website/static/src/js/sh_call_to_action_btn_scroll_js.js",

            # Footer
            "theme_softhealer_website/static/src/scss/footer.scss",

            # Youtube video player
            "theme_softhealer_website/static/src/xml/youtube_video_player.xml",
            "theme_softhealer_website/static/src/js/youtube_video_player.js",

            # Upcoming Feature
            'theme_softhealer_website/static/src/js/upcoming_feature.js',

            # Blogs 
            'theme_softhealer_website/static/src/scss/blogs_bkp/bhediya_movie_blog_page.scss',
            'theme_softhealer_website/static/src/scss/blogs_bkp/birthday_celebration_team_building_blog_page.scss',
            'theme_softhealer_website/static/src/scss/blogs_bkp/christmas_celebration_2021_blog_page.scss',
            'theme_softhealer_website/static/src/scss/blogs_bkp/christmas_celebration_2022_blog_page.scss',
            'theme_softhealer_website/static/src/scss/blogs_bkp/fun_activity.scss',
            'theme_softhealer_website/static/src/scss/blogs_bkp/customer_visit_softhealer_blog_page.scss',
            'theme_softhealer_website/static/src/scss/blogs_bkp/gir_trip_blog_page.scss',
            'theme_softhealer_website/static/src/scss/blogs_bkp/group_discussion_blog_page.scss',
            'theme_softhealer_website/static/src/scss/blogs_bkp/kgf_movie_party_blog_page.scss',
            'theme_softhealer_website/static/src/scss/blogs_bkp/navratri_celebration_blog_page.scss',
            'theme_softhealer_website/static/src/scss/blogs_bkp/office_snack_party_blog_page.scss',
            'theme_softhealer_website/static/src/scss/blogs_bkp/republic_day_blog_page.scss',
            'theme_softhealer_website/static/src/scss/blogs_bkp/softhealer_anniversary_blog_page.scss',
            'theme_softhealer_website/static/src/scss/blogs_bkp/9th_anniversary_blog_page.scss',
            'theme_softhealer_website/static/src/scss/blogs_bkp/work_anniversary_celebration_blog_page.scss',
            'theme_softhealer_website/static/src/scss/blogs_bkp/republic_day_2024_blog_page.scss',
            'theme_softhealer_website/static/src/scss/custom_addons_blog_page.scss',
            'theme_softhealer_website/static/src/scss/blogs_bkp/cooking_competition_blog_page.scss',
            'theme_softhealer_website/static/src/scss/blogs_bkp/cricket_tournament_blog_page.scss',
            'theme_softhealer_website/static/src/scss/blogs_bkp/amazing_ahmdabad_trip_blog_page.scss',
            'theme_softhealer_website/static/src/scss/blogs_bkp/table_tennis_blog_page.scss',
            'theme_softhealer_website/static/src/scss/blogs_bkp/carrom_tournament_blog_page.scss',
            'theme_softhealer_website/static/src/scss/blogs_bkp/chess_tournament_blog_page.scss',
            'theme_softhealer_website/static/src/scss/blogs_bkp/blood_donation_blog_page.scss',
            'theme_softhealer_website/static/src/scss/blogs_bkp/bhajiya_party_blog_page.scss',
            'theme_softhealer_website/static/src/scss/blogs_bkp/independence_day_blog_page.scss',
            'theme_softhealer_website/static/src/scss/blogs_bkp/stree_2_movie_blog_page.scss',
            'theme_softhealer_website/static/src/scss/blogs_bkp/ganesh_chaturthi_blog_page.scss',
            'theme_softhealer_website/static/src/scss/blogs_bkp/garba_night_2024_blog_page.scss',
            'theme_softhealer_website/static/src/scss/blogs_bkp/diwali_celebration_blog_page.scss',
            'theme_softhealer_website/static/src/scss/blogs_bkp/client_visit.scss',
            'theme_softhealer_website/static/src/scss/blogs_bkp/pushpa_2.scss',
            'theme_softhealer_website/static/src/scss/blogs_bkp/heal_station.scss',
            'theme_softhealer_website/static/src/scss/blogs_bkp/cooking_competition_2025.scss',
            'theme_softhealer_website/static/src/scss/blogs_bkp/cricket_Tournament_2025.scss',
            'theme_softhealer_website/static/src/scss/blogs_bkp/women_day_2025.scss',
            'theme_softhealer_website/static/src/scss/blogs_bkp/Artistry_Competition_2025.scss',
            'theme_softhealer_website/static/src/scss/blogs_bkp/chess_tournament_2025.scss',
            'theme_softhealer_website/static/src/scss/blogs_bkp/carrom_tournament_2025.scss',
            'theme_softhealer_website/static/src/scss/blogs_bkp/deadshot_tournament_blog_page.scss',
            'theme_softhealer_website/static/src/xml/sh_s_dynamic_snippet_template.xml',
            'theme_softhealer_website/static/src/js/dynamic_snippet.js',
            'theme_softhealer_website/static/src/js/sh_image_slider.js',
            'theme_softhealer_website/static/src/js/isotope.pkgd.min.js',
            'theme_softhealer_website/static/src/js/sh_cricket_tournament_player_filter.js',
            
            # Home Page JS
            'theme_softhealer_website/static/src/js/home_page.js'


        ],
    },
    'images': [],
    'auto_install': False,
    'installable': True,
    'application': False,
    'license': 'OPL-1',
    'price': '35',
    'currency': 'EUR'
}
